Ft/bundlr fee support
textury/arkb pull request #35
Opened 2021-11-13 14:07 UTC by fuadop

2021-11-15 14:01 UTC, cedriking requested changes
Hey @fuadop I sent some information to review and update.

2021-11-15 14:01 UTC, cedriking commented on src/commands/balance.ts
> +        const res = await bundler.get(`/account/balance?address=${addy}`);
I noticed that this one to get the address is being called here and https://github.com/textury/arkb/pull/35/files#diff-0cb87263fc2cd13d57e280a254b560b49292258ea6134b4d08b1ba2ebf1eea63R48 , let's best use a single call that will be available in the bundler class here: https://github.com/textury/arkb/blob/01b9fecba930b65c7d758e017a723aa2fed87053/src/utils/bundler.ts

2021-11-16 09:45 UTC, fuadop commented on src/commands/fundBundler.ts
> +      tx.reward = parseInt(tx.reward, 10).toString();
@cedriking what does a multiplier do ? it multiplies the reward ?

2021-11-16 10:11 UTC, fuadop commented
Hello @cedriking ,

Can you please review now ?

2021-11-16 12:30 UTC, cedriking commented on src/commands/withdrawBundler.ts
> +  aliases: ['wb'],
No alias for this one please

2021-11-16 12:36 UTC, cedriking requested changes
Only ones I've noticed that are missing is changing to the Transfer class, and removing the alias on withdraw-bundler. Thanks @fuadop !

2021-11-16 12:36 UTC, cedriking commented on src/commands/fundBundler.ts
> +      const tx = await blockweave.createTransaction(
We should use the Transfer class here: https://github.com/textury/arkb/blob/master/src/lib/transfer.ts

2021-11-16 16:43 UTC, fuadop commented
@cedriking

2021-11-16 17:19 UTC, merged